### ISSUE TITLE
Visual Studio 2008 x64 patch for AppVeyor is incomplete for command-line builds

### ISSUE THREAD

**Issue by TBBle** [scikit-build/scikit-ci-addons#35]
In order to get a working VS2008 x64 compile working, I had to do the following: (See mhils/libxml2-win-binaries#9)
````powershell
            # http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#patch-vs2008-py
            C:\Python27\python -m pip install scikit-ci-addons
            C:\Python27\python -m ci_addons appveyor/patch_vs2008
            # http://help.appveyor.com/discussions/kb/38-visual-studio-2008-64-bit-builds
            Copy-Item "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"
````

As noted, the process was documented at http://help.appveyor.com/discussions/kb/38-visual-studio-2008-64-bit-builds and the existing patch takes care of the `setup_x64.bat` part of that description.

The difference is visible from https://ci.appveyor.com/project/TBBle/libxml2-win-binaries/build/1.0.66/job/kgdmrkwp20bs8s04 to https://ci.appveyor.com/project/TBBle/libxml2-win-binaries/build/1.0.67/job/pmm5qnga2uqbfs3x after the application of https://github.com/TBBle/libxml2-win-binaries/commit/e55a7a44b044ba7bdbb1276974f116151f7ed36d.

I haven't tested it, but I believe the patch as-packaged works for IDE-based builds, which don't rely on `vcvars.bat` working.

It's also worth noting this entire patch does not appear to be necessary for building Python wheels, as AppVeyor slaves include the [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-au/download/details.aspx?id=44266) which setuptools 6 can detect and use, removing the need for a Visual Studio 2008 installation.

**Comment by jcfr** [comment]
Hi TBBle,

Thanks a lot for the detailed report.

I will be addressing the issue later this week and also add test.

Jc



On Feb 18, 2017 9:21 AM, "TBBle" <notifications@github.com> wrote:

In order to get a working VS2008 x64 compile working, I had to do the
following:

            # http://scikit-ci-addons.readthedocs.io/en/latest/addons.html#patch-vs2008-py
            C:\Python27\python -m pip install scikit-ci-addons
            C:\Python27\python -m ci_addons appveyor/patch_vs2008
            # http://help.appveyor.com/discussions/kb/38-visual-studio-2008-64-bit-builds
            Copy-Item "C:\Program Files (x86)\Microsoft Visual Studio
9.0\VC\bin\vcvars64.bat" "C:\Program Files (x86)\Microsoft Visual
Studio 9.0\VC\bin\amd64\vcvarsamd64.bat"

As noted, the process was documented at http://help.appveyor.com/
discussions/kb/38-visual-studio-2008-64-bit-builds and the existing patch
takes care of the setup_x64.bat part of that description.

The difference is visible from https://ci.appveyor.com/
project/TBBle/libxml2-win-binaries/build/1.0.66/job/kgdmrkwp20bs8s04 to
https://ci.appveyor.com/project/TBBle/libxml2-win-binaries/build/1.0.67/job/
pmm5qnga2uqbfs3x after the application of TBBle/libxml2-win-binaries@e55a7a4
<https://github.com/TBBle/libxml2-win-binaries/commit/e55a7a44b044ba7bdbb1276974f116151f7ed36d>
.

I haven't tested it, but I believe the patch as-packaged works for
IDE-based builds, which don't rely on vcvars.bat working.

It's also worth noting this entire patch does not appear to be necessary
for building Python wheels, as AppVeyor slaves include the Microsoft Visual
C++ Compiler for Python 2.7
<https://www.microsoft.com/en-au/download/details.aspx?id=44266> which
setuptools 6 can detect and use, removing the need for a Visual Studio 2008
installation.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/scikit-build/scikit-ci-addons/issues/35>, or mute the
thread
